// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      // return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      // case TargetPlatform.iOS:
      //   return ios;
      // case TargetPlatform.macOS:
      //   return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  // static const FirebaseOptions web = FirebaseOptions(
  //   apiKey: 'AIzaSyDbi86OpBGyd_eNx4qjuboLrT4SgOo2NGc',
  //   appId: '1:908904555856:web:ed9d5c365ba4c86bacb855',
  //   messagingSenderId: '908904555856',
  //   projectId: 'my-todoo-app',
  //   authDomain: 'my-todoo-app.firebaseapp.com',
  //   storageBucket: 'my-todoo-app.appspot.com',
  //   measurementId: 'G-6811GS1GCT',
  // );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_tNK0ORmdqNPukpgwrxv_qr0P2gHnnI4',
    appId: '1:908904555856:android:866d1f44f91a5b55acb855',
    messagingSenderId: '908904555856',
    projectId: 'my-todoo-app',
    storageBucket: 'my-todoo-app.appspot.com',
  );

  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyDZKb99mTp3RLz3apXdzMKNQD0IFYjQa54',
  //   appId: '1:908904555856:ios:5d016f0db402df04acb855',
  //   messagingSenderId: '908904555856',
  //   projectId: 'my-todoo-app',
  //   storageBucket: 'my-todoo-app.appspot.com',
  //   iosBundleId: 'com.example.myTodooApp',
  // );

  // static const FirebaseOptions macos = FirebaseOptions(
  //   apiKey: 'AIzaSyDZKb99mTp3RLz3apXdzMKNQD0IFYjQa54',
  //   appId: '1:908904555856:ios:b96c12555bd07466acb855',
  //   messagingSenderId: '908904555856',
  //   projectId: 'my-todoo-app',
  //   storageBucket: 'my-todoo-app.appspot.com',
  //   iosBundleId: 'com.example.myTodooApp.RunnerTests',
  // );
}
